---
- hosts: prueba:prueba2
  gather_facts: true
  become: yes
  become_method: sudo
  roles:
    - init_configuration
    - install_docker
    - install_kubernetes

- hosts: prueba
  gather_facts: true
  become: yes
  become_method: sudo
  roles:
    - cluster_config/first_master

- hosts: prueba2
  gather_facts: true
  become: yes
  become_method: sudo
  roles:
    - cluster_config/new_master  