---
- hosts: firstcontroller:controllers:workers
  gather_facts: true
  become: yes
  become_method: sudo
  roles:
    - init_configuration
    - install_docker
    - install_kubernetes

- hosts: firstcontroller
  gather_facts: true
  become: yes
  become_method: sudo
  roles:
    - cluster_config/first_master

- hosts: controllers
  gather_facts: true
  become: yes
  become_method: sudo
  roles:
    - cluster_config/new_master  

- hosts: workers
  gather_facts: true
  become: yes
  become_method: sudo
  roles:
    - cluster_config/worker  