---
- hosts: firstcontroller:controller:workerprueba
  gather_facts: true
  become: yes
  become_method: sudo
  roles:
    - init_configuration
    - install_docker
    - install_kubernetes

- hosts: firstcontroller
  gather_facts: true
  become: yes
  become_method: sudo
  roles:
    - cluster_config/first_master

- hosts: controller
  gather_facts: true
  become: yes
  become_method: sudo
  roles:
    - cluster_config/new_master  

- hosts: workerprueba
  gather_facts: true
  become: yes
  become_method: sudo
  roles:
    - cluster_config/worker  