---
- name: Update repositorys
  apt: 
    update_cache: yes 
    force_apt_get: yes
  become: true
    
- name: Install packages to allow apt to use a repository over HTTPS
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    autoclean: yes
    update_cache: yes
  become: true

- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
  become: true

- name: Install docker engine
  apt:
    update_cache: yes
    name: 
    - docker-ce
    - docker-ce-cli
    - containerd.io
    autoclean: yes
  become: true

- name: Configure docker
    copy:
      mode: 0644
      dest: /etc/docker/daemon.json
      content: |
        {
          "exec-opts": ["native.cgroupdriver=systemd"]
        }
  become: true

- name: Restart service docker
  service:
    name: docker
    state: restarted
  become: true