---
- name: Copy join controller command
  copy:
    src: "~/joincontroller"
    dest: "joincontroller"

- name: Init controller node
  shell: sh joincontroller | tee result
  register: init_controller