---
- name: Copy join controller command
  copy:
    src: "joincontroller"
    dest: "joincontroller"

- name: Init controller node
  shell: sh {{ hostvars['prueba']['join'] }} | tee result
  register: init_controller