---

- name: Copy joincontroller to the controller
  copy:
    src: "~/joincontroller"
    dest: "joincontroller"
    mode: 0755

- name: Init worker node
  shell: sh joincontroller 2>&1 | tee result
  register: init_controller