---

- name: Reset Kubernetes component
  shell: kubeadm reset --force
  become: true
  register: reset_controller

- name: Copy join controller command
  copy:
    src: "~/joincontroller"
    dest: "joincontroller"

- name: Verify ip forward in 1
  when: reset_controller is succeeded
  shell: echo 1 | sudo tee /proc/sys/net/ipv4/ip_forward

- name: Init controller node
  when: reset_controller is succeeded
  shell: sh joincontroller 2>&1 | tee result
  register: init_controller