---
- name: Add the br_netfilter module
  shell: modprobe br_netfilter
  become: true

- name: Turn swap off
  shell: swapoff -a

- name: Add netbridge config ipv6
  lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: 'net.bridge.bridge-nf-call-ip6tables = 1'
    state: present
    create: yes

- name: Add netbridge config ipv4
  lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: 'net.bridge.bridge-nf-call-iptables = 1'
    state: present
    create: yes

- name: Restart sysctl
  shell: sysctl --system
  become: true