---

- name: Reset Kubernetes component
  shell: kubeadm reset --force
  become: true
  register: reset_cluster

- name: Verify ip forward in 1
  when: reset_cluster is succeeded
  shell: echo 1 | sudo tee /proc/sys/net/ipv4/ip_forward

- name: Init Kubernetes cluster
  when: reset_cluster is succeeded
  shell: |
    kubeadm init \
      --control-plane-endpoint "{{ cp_endpoint }}" \
      --upload-certs \
      --pod-network-cidr "{{ pod_cidr }}" 2>&1 | tee result
  register: init_cluster

- name: Create Kubernetes config directory
  file:
    path: ".kube/"
    state: directory

- name: Copy admin.conf to Home directory
  when: init_cluster is succeeded
  copy:
    src: "{{ kubeadmin_config }}"
    dest: ".kube/config"
    mode: 0755
    remote_src: true

- name: Apply the CNI deployment
  shell: kubectl apply -f https://raw.githubusercontent.com/movie-analyst/movie-analyst-cm/master/kube-flannel.yaml
  become: false
