---

- name: Check if kubeadm has already run
  stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- name: Init cluster if needed
  include_tasks: init.yaml
  when: not kubeadm_ca.stat.exists
  run_once: yes

- name: Enable and check kubelet service
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes
  register: started_kubelet

- name: "Copy config file to ansible server"
  fetch:
    src: "{{ kubeadmin_config }}"
    dest: "{{ lookup('env', 'HOME') }}/config"
    flat: yes
  run_once: yes
  ignore_errors: yes

- name: Generate join command
  shell: kubeadm token create --print-join-command
  register: join

- name: Copy join command to ansibleserver
  when: join is succeeded
  copy:
    content: "{{ join.stdout }}"
    dest: "/var/kubernetes/join"

- name: Generate certificates
  shell: kubeadm init phase upload-certs --upload-certs | tail -1 
  register: certificate

- name: Copy certificate to ansibleserver
  when: certificate is succeeded
  copy:
    content: "{{ certificate.stdout }}"
    dest: "/var/kubernetes/certificate"