---

- name: Check if kubeadm has already run
  stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- name: Init cluster if needed
  include_tasks: init.yaml
  when: not kubeadm_ca.stat.exists
  run_once: yes

- name: Enable and check kubelet service
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes
  register: started_kubelet

- name: "Copy config file to ansible server"
  fetch:
    src: "{{ kubeadmin_config }}"
    dest: "{{ lookup('env', 'HOME') }}/config"
    flat: yes
  run_once: yes
  ignore_errors: yes

- name: Generate join command
  shell: kubeadm token create --print-join-command | tee join

- name: "Copy join file to ansible server"
  fetch:
    src: ~/join
    dest: "{{ lookup('env', 'HOME') }}/join"
    flat: yes
  run_once: yes
  ignore_errors: yes
  become: false