---

- name: Check if kubeadm has already run
  stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- name: Init cluster if needed
  include_tasks: init.yml
  when: not kubeadm_ca.stat.exists
  run_once: yes

- name: Enable and check kubelet service
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes
  register: started_kubelet

- name: "Copy config file to ansible server"
  fetch:
    src: /etc/kubernetes/admin.conf 
    dest: "{{ lookup('env', 'HOME') }}/config"
    flat: yes
  run_once: yes
  ignore_errors: yes

- name: "Copy join controller file to ansible server"
  fetch:
    src: ~/joincontroller
    dest: "{{ lookup('env', 'HOME') }}/joincontroller"
    flat: yes
  run_once: yes
  ignore_errors: yes

- name: "Copy joinworker to ansible server"
  fetch:
    src: ~/joinworker
    dest: "{{ lookup('env', 'HOME') }}/joinworker"
    flat: yes
  run_once: yes
  ignore_errors: yes